config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :public do
    get 'homes/top'
    get 'homes/about'
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources :items, only: [:index, :show]
    resource :customers, only: [:edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    resources :shipping_address, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    get 'homes/top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    return '〒'+ postal_code+" "+address+" "+name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #def full_name
    #first_name + last_name
  #end
  has_many :orders
  has_many :cart_items
  has_many :addresses
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1, production: 2, preparing: 3, sent: 4 }
  def amount_all
    sum = 0
    self.order_details.each do |order_detail|
      sum+= order_detail.amount
    end
    return sum
  end
  def full_address
    return '〒'+ postal_code+" "+address+" "+name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :order
   belongs_to :item
   enum making_status: { productionnotallowed: 0, waitingforproduction: 1, underconstruction: 2, productioncompleted: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end

  private

  def order_prams
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :order_status)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all

  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :id, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "confirmation"
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: "waitingforproduction")
      end
    end
    if @order.order_details == "underconstruction"
      @order.update(order_status: "production")
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :order_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]


  def after_sign_in_path_for(resource)
    admin_homes_top_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
   case resource
   when Admin
     admin_homes_top_path
   when Customer
     public_homes_top_path
   end
  end

 def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      public_homes_top_path
    end
 end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>

<%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
  <%= f.label :ジャンル名 %>
  <%= f.text_field :name %>
  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>

<%= form_with model: @genre, url: admin_genres_path do |f| %>
  <%= f.label :ジャンル名 %>
  <%= f.text_field :name %>
  <%= f.submit '新規登録' %>
<% end %>


<% @genres.each do |genre| %>
  <%= genre.name %>
  <%= link_to "編集する", edit_admin_genre_path(genre.id) %>
<% end %>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>

  <%= form_with model: @item, url: admin_item_path do |f| %>
    <h4>商品画像</h4>
    <%= f.file_field :image %>

    <h4>商品名</h4>
    <%= f.text_field :name %>

    <h4>商品説明</h4>
    <%= f.text_area :introduction %>

    <h4>ジャンル</h4>
    <%= f.collection_select(:genre_id, @genres, :id, :name) %>

    <h4>税抜価格</h4>
    <%= f.text_field :price %>円

    <h4>販売ステータス</h4>
    <%= f.label :is_active, "販売中", value: true %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, "販売停止中", value: false %>
    <%= f.radio_button :is_active, false %>

    <%= f.submit '変更を保存' %>
  <% end %>

app/views/admin/items/index.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2>商品一覧</h2>
        <%= link_to new_admin_item_path do %>
          <i class="fas fa-plus"></i>
        <% end %>
        <table>
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active %>
                販売中
                <% else %>
                販売停止中
                <% end %>
              </td>
            </tr>

            <% end %>

          </tbody>
        </table>
        <%= paginate @items %>
      </div>
    </div>
  </div>
</body>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>

  <%= form_with model: @item, url: admin_items_path do |f| %>
    <h4>商品画像</h4>
     <%= f.file_field :image %>

    <h4>商品名</h4>
    <%= f.text_field :name %>

    <h4>商品説明</h4>
    <%= f.text_area :introduction %>

    <h4>ジャンル</h4>
    <%= f.collection_select(:genre_id, @genres, :id, :name, include_blank: "--選択して下さい--") %>

    <h4>税抜価格</h4>
    <%= f.text_field :price %>円

    <h4>販売ステータス</h4>
    <%= f.label :is_active, "販売中", value: true %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, "販売停止中", value: false %>
    <%= f.radio_button :is_active, false %>

    <%= f.submit '新規登録' %>
  <% end %>

app/views/admin/items/show.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2>商品詳細</h2>

        <table>
          <tbody>
            <tr>

              <%= image_tag @item.image, size: '320x240' %>

              <td>
                <h4>商品名</h4><%= @item.name %>
              </td>

              <td>
                <h4>商品説明</h4><%= @item.introduction %>
              </td>

              <td>
                <h4>ジャンル</h4><%= @item.genre.name %>
              </td>

              <td>
                <h4>税込価格</h4><%= @item.price %>円
              </td>

              <td>
                <h4>販売ステータス</h4>
                <% if @item.is_active %>
                販売中
                <% else %>
                販売停止中
                <% end %>
              </td>

              <td>
                <%= link_to "編集する", edit_admin_item_path(@item.id)  %>
              </td>

            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</body>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h2>注文履歴詳細</h2>

      <h4>購入者</h4><%= link_to @order.name, admin_customer_path(@customer.id) %>
      <h4>注文日</h4><%= @order.created_at %>
      <div>
        <h4>配送先</h4>〒<%= @order.postal_code %><%= @order.address %><%= @customer.last_name %><%= @customer.first_name %>
      </div>
      <h4>支払方法</h4><%= @order.payment_method_i18n %>
      <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
        <h4>注文ステータス</h4><%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
        <%= f.submit '更新' %>
      <% end %>
    </div>

      <div class="col-sm-8">
        <table>
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th>制作ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.price * order_detail.amount %></td>
              <%= form_with model: order_detail, url: admin_order_order_detail_path(order_id: @order.id, id: order_detail.id) do |f| %>
                <td><%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %></td>
                <td><%= f.submit '更新' %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
        <table>
          <tr>
            <th>商品合計</th>
            <td><%= @order.total_payment - 800 %></td>
          </tr>
          <tr>
            <th>配送料</th>
            <td>800</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= @order.total_payment %></td>
          </tr>
        </table>
      </div>
  </div>
</div>