config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  namespace :public do
    get 'homes/top'
    get 'homes/about'
    get "/customers/my_page" => "customers#show"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdrawal" => "customers#withdrawal"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources :items, only: [:index, :show]
    resource :customers, only: [:edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :orders, only: [:new, :create, :index, :show]
    resources :shipping_address, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    get 'homes/top'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    return '〒'+ postal_code+" "+address+" "+name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #def full_name
    #first_name + last_name
  #end
  has_many :orders
  has_many :cart_items
  has_many :addresses
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1, production: 2, preparing: 3, sent: 4 }
  def amount_all
    sum = 0
    self.order_details.each do |order_detail|
      sum+= order_detail.amount
    end
    return sum
  end
  def full_address
    return '〒'+ postal_code+" "+address+" "+name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :order
   belongs_to :item
   enum making_status: { productionnotallowed: 0, waitingforproduction: 1, underconstruction: 2, productioncompleted: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page])
  end

  private

  def order_prams
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :order_status)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all

  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :id, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
   case resource
   when Admin
     admin_homes_top_path
   when Customer
     public_homes_top_path
   end
  end

 def after_sign_out_path_for(resource)
    case resource
    when :admin   # ログアウト時はシンボルが返ってくる
      new_admin_session_path
    when :customer  # ログアウト時はシンボルが返ってくる
      public_homes_top_path
    end
 end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container">
    <div class="row">
      <div class="col">
        <body>
          <header>
                    <% if admin_signed_in? %>
                    <li>
                      <i class="fas fa-home"></i>
                      <%= link_to "商品一覧", admin_items_path %>
                    </li>
                    <li>
                      <i class="fas fa-link"></i>
                      <%= link_to "会員一覧", admin_customers_path %>
                    </li>
                    <li>
                      <i class="fas fa-user-plus"></i>
                      <%= link_to "注文履歴一覧", admin_homes_top_path %>
                    </li>
                    <li>
                      <i class="fas fa-sign-in-alt"></i>
                      <%= link_to "ジャンル一覧", admin_genres_path %>
                    </li>
                    <li>
                      <i class="fas fa-sign-in-alt"></i>
                      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
                    </li>

                    <% elsif customer_signed_in?%>
                    <li>
                      <i class="fas fa-sign-in-alt"></i>
                      <%= link_to "マイページ", public_customers_my_page_path %>
                    </li>
                    <li>
                      <i class="fas fa-sign-in-alt"></i>
                      <%= link_to "商品一覧", public_items_path %>
                    </li>
                    <li>
                      <i class="fas fa-sign-in-alt"></i>
                      <%= link_to "カート", public_cart_items_path %>
                    </li>
                    <li>
                      <i class="fas fa-sign-in-alt"></i>
                      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
                    </li>

                    <% else %>
                    <li>
                      <i class="fas fa-home"></i>
                      <%= link_to "About", public_homes_about_path %>
                    </li>
                    <li>
                      <i class="fas fa-users"></i>
                      <%= link_to "商品一覧", admin_items_path %>
                    </li>
                    <li>
                      <i class="fas fa-book-open"></i>
                      <%= link_to "新規登録", new_customer_registration_path %>
                    </li>
                    <li>
                      <i class="fas fa-sign-out-alt"></i>
                      <%= link_to "ログイン", new_customer_session_path %>
                    </li>
                    <% end %>
          </header>
          <%= yield %>
        </body>
      </div>
    </div>
  </div>
</html>